services:
  db:
    build: ./db
    restart: always
    container_name: ${PROJECT_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_INITIAL_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=5432
    networks:
      docker_portfolio_network:
        ipv4_address: 172.35.0.2
  web:
    build: ./web
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
    container_name: ${PROJECT_NAME}_web
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    depends_on:
      - db
    volumes:
      - ./web:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    networks:
      docker_portfolio_network:
        ipv4_address: 172.35.0.3

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:

networks:
  docker_portfolio_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/16